name: social
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  dio: ^5.3.2
  intl: ^0.18.0
  get_storage: ^2.1.1
  logger: ^1.3.0
  shamsi_date: ^1.0.1
  sms_autofill: ^2.3.0
  device_info_plus: ^9.0.2
  package_info_plus: ^4.2.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^3.0.4
  angles: ^2.1.1
  local_auth: ^2.1.6
  android_alarm_manager_plus: ^3.0.1
  permission_handler: any
  share_plus: ^7.0.0
  dotted_border: ^2.0.0+3
  dotted_line: ^3.2.2
  pdf: ^3.10.4
  open_file_plus: ^3.4.1
  dartz: ^0.10.1
  image_sequence_animator: ^2.0.0

  # Presentation packages
  responsive_framework: ^0.2.0
  flutter_svg: ^2.0.4
  pin_code_fields: ^7.4.0
  auto_size_text: ^3.0.0
  figma_squircle: ^0.5.3
  lottie: ^2.3.2
  loading_indicator: ^3.1.0
  nil: ^1.1.1
  scrollable_positioned_list: ^0.3.5
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  persian_datetime_picker: ^2.5.0
  flutter_ringtone_player: ^3.2.0
  story_view: ^0.15.0
  html2md: ^1.3.1
  flutter_markdown: ^0.6.17
  cached_network_image: ^3.2.3
  badges: ^3.1.1
  flutter_rating_bar: ^4.0.1
  persian_number_utility: ^1.1.3
  mockito: ^5.4.2
  app_links: ^3.4.3
  flutter_local_notifications: ^15.1.1
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  vibration: ^1.8.1
  dots_indicator: ^3.0.0
  persian_tools: ^1.0.3
  path_provider: ^2.0.1
  mocktail: ^1.0.0
  equatable: ^2.0.5
  just_audio: ^0.9.36
  #  audio_waveforms: ^1.0.4
  uuid: ^3.0.7
  image_picker: ^1.0.7
  flutter_image_compress: ^2.1.0
  image_cropper: ^5.0.1
  file_picker: ^6.1.1
  flutter_cache_manager: ^3.3.1
  flutter_web_frame: ^1.0.0
  blur: ^3.1.0
  glass_kit: ^3.0.0


  # chat_composer dependencies
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  fluttertoast: ^8.0.9
  flutter_sound_lite: ^8.5.0
  # end chat composer dependencies



  taakitecture:
    git:
      url: git@github.com:TaakGroup/taakitecture.git
      ref: main


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.6
  rename_app: ^1.3.1
  fl_chart: ^0.66.0
  pulsator: ^1.0.0+2
  glowy_borders: ^1.0.2

  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.social
        pluginClass: SocialPlugin
      ios:
        pluginClass: SocialPlugin
      web:
        pluginClass: SocialWeb
        fileName: social_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
