// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUUA1jtph8jhTlSjSawieq1uQWDvzlPK8',
    appId: '1:675040069016:web:f14c2d55a4f6fd9d8c17ed',
    messagingSenderId: '675040069016',
    projectId: 'impodoctor',
    authDomain: 'impodoctor.firebaseapp.com',
    storageBucket: 'impodoctor.appspot.com',
    measurementId: 'G-05FNYH442F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJCfPKU_MeeWZRiIMX_KAvenQiSiLKEw4',
    appId: '1:675040069016:android:11c058778545ceb38c17ed',
    messagingSenderId: '675040069016',
    projectId: 'impodoctor',
    storageBucket: 'impodoctor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZuhFPVpb3VpWSJkGPUeP2nMlg4mnnt_4',
    appId: '1:675040069016:ios:5938d7d4603c36958c17ed',
    messagingSenderId: '675040069016',
    projectId: 'impodoctor',
    storageBucket: 'impodoctor.appspot.com',
    iosBundleId: 'com.impo.impoDoctor',
  );
}
